server:
  port: 8080
  servlet:
    context-path: /eml/v1
spring:
    application:
        name: employee-leave-management
    datasource:
        driver-class-name: org.postgresql.Driver
        password: Admin
        url: jdbc:postgresql://localhost:5432/employee_leave_requests
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
